### ISSUE TITLE
Umožnit animaci při zavření pdboxu

### ISSUE THREAD

**Issue by zipper** [peckadesign/jquery.pdbox#10]
Při zavření pdboxu dojde k okamžitému smazání z DOM. Kvůli tomu není možné přes CSS animovat skrytí pdboxu. Možné řešení by bylo např. nastavit dobu mezi `beforeClose` a samotným smazáním a událostí `afterClose`. Při `beforeClose` by se na pdboxu mohla nastavit například class `pdbox--is-closing`, případně by mohlo dojít k nastavení nějakých class s využitím callbacku `onBeforeClose`.

Prosím o případné připomínky @peckadesign/koderi.

**Comment by radeksir** [comment]
Ta class ``pdbox--is-closing`` by byla dobrá, akorát nevím jak pak volit ten čas, kdy opravdu zmizí box z DOM. Projekťáci při testování občas klikají jak šílení a někdy i klient, takže i zproždění 1s by mohlo být problém.

1. myslím, že class určitě
2. do option dát parametr za jak dlouho vymazat z DOM, defaultně to bude 0ms a šlo by nastavit pak třeba na klasických 300ms

**Comment by zipper** [comment]
Délka animace bude řešená podobným způsobem, jako v #10 šířka scrollbaru. Načítal bych proměnnou z CSS, pokud nebude, bude automaticky zpoždění 0ms. Díky tomu bude stačit mít nastavenu tu hodnotu jen na jednom místě a nebude potřeba vůbec na straně JS řešit.

**Comment by zipper** [comment]
Hotovo, čeká na release.
