### ISSUE TITLE
Podpora videa současně s obrázky

### ISSUE THREAD

**Issue by premyslposker** [peckadesign/jquery.pdbox#2]
při skupině obrázků mít možnost přidat do skupiny i video (a mít vše provázané stránkováním)

**Comment by premyslposker** [comment]
@zipper prosím o kontrolu

**Comment by zipper** [comment]
Díky, pár věcí bych k tomu měl.
- Po načtení se nebude spouštět load event thickboxu, což může být potenciálně problém a je to nekonzistentní chování (jak obrázky, obyčejné html, tak AJAX obsah spouští událost load). Celkově by se to dalo asi zjednodušit jednotným přístupem k obrázkům a videům (load calback atd.).
- Trochu se mi nelíbí ten div, který jsi tam přidal do (`pd-box-img-wrapper`), pokud není nezbytně nutný, určitě bych ho tam nedával. Naopak bych rád přidal možnost nadefinovat vlastní html (založím si na to úkol) strukturu.
- Některé atributy bych úplně neuváděl. Určitě vyhodit `frameborder`, šířka a výška jsou taky asi víceméně zbytečné (budou nepochybně přepsané přes CSS), ale asi můžou zůstat. Možná by mohly v takovém případě přebírat nastavení thickboxu (šířka, výšku dopočítat).

**Comment by petrzdansky** [comment]
viz: video na Nay: https://www.nay.sk/braun-eb-20-4-3-nahr-kefky-3-1

**Comment by zipper** [comment]
@premyslposker Upravil jsem to, vyzkoušel jsem, mělo by to fungovat, mohl bys prosím úpravu nasadit na Nay a @petrzdansky ještě jednou zkontrolovat? Pak bych udělal merge do masteru.

**Comment by premyslposker** [comment]
@zipper otestováno na NAY, kde to funguje - @petrzdansky jakmile se zamerguje, můžeme nasadit

**Comment by petrzdansky** [comment]
@premyslposker Přmeku, jaké vzniknout rozdíly oproti současné verzi na Nay? Resp. pokud to mám někde zkontrolovat, tak to asi potřebuji mít možnost někde vyzkoušet.

**Comment by zipper** [comment]
Je to v masteru, @premyslposker může nasadit na Nay (jestli ještě není).
