### ISSUE TITLE
Oprava zakončení tagu náhledu

### ISSUE THREAD

**Issue by premyslposker** [peckadesign/jquery.pdbox#26]
Při generování náhledů v pdboxu není zakončen tag `li`

**Comment by premyslposker** [comment]
@zipper
- hotovo ve větvi `26-thumbnail-tag-close`
- PR projekt https://github.com/peckadesign/jquery.pdbox/pull/27

**Comment by zipper** [comment]
Prosím uprav ještě verzi ve všech souborech (krom dist a poté ještě jednou vygruntovat), díky. Případně doplnit changelog.

**Comment by premyslposker** [comment]
@zipper upraveno a doplněno ;)

**Comment by zipper** [comment]
Díky, zamergeováno a vydána verze 1.3.10 👍
