### ISSUE TITLE
Možnost nadefinovat vlastní html strukturu pdBoxu

### ISSUE THREAD

**Issue by zipper** [peckadesign/jquery.pdbox#3]
Název hovoří za vše. Při inicializaci pdBoxu udělat jednorázovou (tj. nebude možno měnit později přes data atributy např.) možnost změnit strukturu html kódu.

V rámci této změny by se měl také ve výchozím nastavení použít spinner z Nette extension, podobně jako zde https://github.com/zipper/jquery.collapsable/blob/1.1.0/jquery.collapsable.js#L155, nebo nějaký defaultní. díky tomu, nebude nutné kvůli jinému spinneru měnit pdBox. V rámci option pro změnu html půjde samozřejmě přepsat též.

@peckadesign/koderi nápady, připomínky?

**Comment by zipper** [comment]
@peckadesign/koderi Je ještě dnes žádoucí zavírat TB kliknutím na obrázek? Nebo mám toto v rámci tohoto úkolu zahodit? Co myslíte?

**Comment by premyslposker** [comment]
@zipper mě se zavírání kliknutím na obrázek nelíbí, ale určitě bych se zeptal i @peckadesign/projektaci

**Comment by Miklo78** [comment]
Těžko říct, osobně bych to klikem na obrázek nezavíral, ale spíš klikem na křížek, anebo klikem mimo thickbox. Takže za mě se asi to zavření přes obrázek může zrušit.

**Comment by zipper** [comment]
S projekťáky (krom Petra, který má dovolenou) jsem to probral a shodli jsme se na tom samém. Nově tedy klik na obrázek nic dělat nebude.
